name: 🚀 Deploy Maven Application on Prod

on:
  push:
    branches:
      [ "main" ]

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST: ${{ secrets.HOST_NAME }}
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Copy files over SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        source: target/*.jar
        target: ~/pepperoni-bot-1.0-SNAPSHOT.jar
        
    - name: Run Remote Command
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd ~/
          java -jar pepperoni-bot-1.0-SNAPSHOT.jar
