name: Deploy Java Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubunto-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Copy Repository Contents Via SCP
    - uses: appleboy/scp-action@main
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/opt/"
    - name: Executing remote command
      uses: appleboy/ssh-action@main
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: ls
