name: 🚀 Deploy Java Application on Prod

on:
  push:
    branches:
      [ "main" ]

env:
  IP: ${{ secrets.HOST_NAME }}
  USERNAME: ${{ secrets.USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pepperoni-bot-1.0-SNAPSHOT.jar
          path: target/pepperoni-bot-1.0-SNAPSHOT.jar

      - name: Deploy to VPS
        uses: actions/ssh-action@v1
        with:
          host: ${{ env.IP }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            sudo systemctl stop Main
            sudo rm /home/pepperoni-bot/pepperoni-bot-1.0-SNAPSHOT.jar
            sudo scp -o StrictHostKeyChecking=no $(System.ArtifactDirectory)/pepperoni-bot-1.0-SNAPSHOT.jar {{ env.USERNAME }}@{{ env.IP }}:/home/pepperoni-bot/pepperoni-bot-1.0-SNAPSHOT.jar
            sudo systemctl start Main
