name: 🚀 Deploy Java Application on Prod

on:
  push:
    branches:
      [ "main" ]

env:
  IP: ${{ secrets.HOST_NAME }}
  USERNAME: ${{ secrets.USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn package

      - name: Deploy to VPS
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.IP }}
          username: ${{ env.USERNAME }}
          private_key: ${{ secrets.VPS_PRIVATE_KEY }}
          source: target/pepperoni-bot-1.0-SNAPSHOT.jar
          target: target/pepperoni-bot-1.0-SNAPSHOT.jar
          scp_args: -o StrictHostKeyChecking=no

      - name: Restart application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.IP }}
          username: ${{ env.USERNAME }}
          private_key: ${{ secrets.PROD_VPS_PRIVATE_KEY }}
          script: |
            sudo systemctl restart Main
