name: Deploy Java Application

on:
  push:
    branches:
      - main

env:
  PATH_APP: /opt/pepperoni-bot


jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Build with Maven
      run: |
        cd $PATH_APP
        mvn clean install
