name: Deploy Java Application

on:
  push:
    branches:
      - main

env:
  PATH_APP: /opt/pepperoni-bot
  SSH_PRIVATE_KEY: ${{ secrets.SSHKEY }}
  SSH_PORT: 22
  SERVER: ${{ secrets.HOST }}
  



jobs:
  deploy:
    runs-on: ubuntu-18.04
    
    steps:
    - name: Check Java version
      run: |
          java -version
          echo $?
    - name: Install Java
      if: steps.check-java.output != '0'
      run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk git
          sudo update-alternatives --config java
          sudo update-alternatives --config javac
  

    - name: Git clone or pull
      env:
          SSHPASS: ${{ env.SSH_PRIVATE_KEY  }}
      run: |
           - sshpass -e ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SERVER -p $SSH_PORT "if [ -d $PATH_APP ]; then rm -rf $PATH_APP; fi; git clone git@github.com:gamartins013/pepperoni-bot.git $PATH_APP"
    - name: Verify directory
      run: |
          ssh -o StrictHostKeyChecking=no $SERVER  -p $SSH_PORT "if [ ! -d $PATH_APP ]; then mkdir -p $PATH_APP; fi"
    - name: Build with Maven
      run: |
          cd $PATH_APP
          mvn clean install
    - name: Connect to Server
      run: |
          ssh -o StrictHostKeyChecking=no $SERVER  -p $SSH_PORT << EOF


