name: Deploy Java Application

on:
  push:
    branches:
      - main

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: shivammathur/setup-ssh-action@v1
      with:
        ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

    - name: SSH Connection
      uses: appleboy/ssh-action@main
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          set -e
          echo "Starting Deployment"
          cd /opt
          git clone ${{ secrets.GIT_REPOSITORY }}
          cd ${{ secrets.APP_NAME }}
          mvn clean install
          java -cp target/classes Main

    - name: Deploy
      uses: ad-m/github-push-action@main
      with:
        ssh_key: ${{ env.SSH_PRIVATE_KEY }}
        branch: master
        git_user: ${{ secrets.GIT_USERNAME }}
        host: ${{ secrets.VPS_HOST }}
        repo: ${{ secrets.APP_NAME }}
