name: 🚀 Deploy Maven Application on Prod

on:
  push:
    branches:
      [ "main" ]

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 11
      
    - name: Build with Maven
      uses: maven-actions/setup-maven@v2
      with:
        maven-version: 3.6.3
        
    - name: Package with Maven
      run: mvn clean package
      
    - name: Copy files over SSH
      uses: appleboy/scp-action@v1
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        source: target/*.jar
        target: ~/pepperoni-bot-1.0-SNAPSHOT.jar
        
    - name: Run Remote Command
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.HOST_NAME }}
        username: ${{ secrets.PUSERNAME }}
        password: ${{ secrets.PASSWORD }}
        key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          cd ~/
          java -jar pepperoni-bot-1.0-SNAPSHOT.jar
